rootProject.name = 'apollo'

include 'shared-lib'
include 'eureka-server'
include 'api-gateway'
include 'auth-service'
include 'operations-service'
include 'reservations-service'
include 'feedback-service'
include 'cocktails-service'
include 'reports-service'
include 'notifications-service'
include 'settings-service'
include 'vouchers-service'
